name: 'GitHub Template Renderer'
author: Patrick Sodre
description: 'A GitHub Action for rendering GitHub Templates'
inputs:
  message:
    description: 'A message to the world'
    required: true
    default: 'Hello World!'
  sender:
    description: 'The sender of the message'
    required: true
    default: 'Peter'
outputs:
  reply:
    description: 'A reply from the world'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'activity'
  color: 'blue'
